import type { Project, IP, TeamMember, PressArticle, JobPosting } from './types';

// ========== DEMO PROJECTS ==========
export const projects: Project[] = [
  {
    slug: 'paco-series',
    title: { vi: 'PACO Series Animation', en: 'PACO Animation Series' },
    client: 'StoryMee Original IP',
    year: 2026,
    category: 'ip',
    services: ['Direction', 'Animation', '3D Production', 'Sound Design'],
    thumbnail: '/assets/paco/ip-paco.jpg',
    gradient: 'linear-gradient(135deg, #0a2e0a 0%, #1b691b 30%, #2d8b2d 60%, #0a0a0b 100%)',
    videoUrl: '/assets/paco/paco-episodes.mp4',
    caseStudy: {
      challenge: { vi: 'Xây dựng series animation 3D cho nhân vật vẹt Paco tạo một IP giáo dục tiếng Anh hài hước giúp người xem học từ vựng và phát âm một cách tự nhiên.', en: 'Building a 3D animation series for the parrot character Paco creating a humorous English education IP that helps viewers learn vocabulary and pronunciation naturally.' },
      approach: { vi: 'Phát triển nhân vật 3D chất lượng Pixar-level với tính cách ngây thơ, luôn "hiểu sai nhưng trung thành tuyệt đối", kết hợp câu chuyện giáo dục nhẹ nhàng.', en: 'Developing Pixar-level 3D characters with naive personality, always "misunderstanding but absolutely loyal", combining gentle educational stories.' },
      outcome: { vi: 'Nhận được sự quan tâm từ nhiều đối tác phát hành quốc tế, fanbase đang phát triển mạnh mẽ.', en: 'Received interest from multiple international distribution partners, fanbase growing rapidly.' },
    },
    credits: [
      { role: 'Creator', name: 'StoryMee Studio' },
      { role: 'Character Design', name: 'StoryMee Art Team' },
      { role: '3D Animation', name: 'StoryMee Animation' },
      { role: 'Sound Design', name: 'StoryMee Audio' },
      { role: 'Cast Paco Nhỏ', name: 'Cute Paco (phiên bản nhỏ)' },
      { role: 'Cast Paco Trưởng Thành', name: 'Young Paco (phiên bản lớn)' },
      { role: 'Cast Paco Già', name: 'Exp Paco (phiên bản già)' },
    ],
  },
  {
    slug: 'bigpaw',
    title: { vi: 'BIGPAW Cuộc Phiêu Lưu', en: 'BIGPAW The Adventure' },
    client: 'StoryMee Original IP',
    year: 2026,
    category: 'ip',
    services: ['Direction', '3D Animation', 'Story Development', 'Post Production'],
    thumbnail: '/assets/bear-poster.jpeg',
    gradient: 'linear-gradient(135deg, #1a0e00 0%, #3d2800 30%, #8B6914 60%, #0a0a0b 100%)',
    videoUrl: '/assets/ip-bear.mp4',
    caseStudy: {
      challenge: { vi: 'Tạo ra nhân vật gấu Bigpaw 3D với tính cách ấm áp, gần gũi, phù hợp cho series animation dành cho trẻ em.', en: 'Creating a 3D Bigpaw character with a warm, relatable personality suitable for a children\'s animation series.' },
      approach: { vi: 'Kết hợp phong cách 3D hiện đại với storytelling truyền thống, tạo ra thế giới tươi sáng và đầy cảm hứng.', en: 'Combining modern 3D style with traditional storytelling, creating a bright and inspiring world.' },
      outcome: { vi: 'IP Bigpaw trở thành một trong những nhân vật được yêu thích nhất của StoryMee, thu hút cộng đồng fan đông đảo.', en: 'Bigpaw IP became one of StoryMee\'s most beloved characters, attracting a large fan community.' },
    },
    credits: [
      { role: 'Creator', name: 'StoryMee Studio' },
      { role: '3D Modeling', name: 'StoryMee Art Team' },
      { role: 'Animation Director', name: 'StoryMee Animation' },
    ],
  },
  {
    slug: 'corgi-u',
    title: { vi: 'Ú Corgi Khu Tập Thể', en: 'Ú Corgi in the Neighborhood' },
    client: 'StoryMee Original IP',
    year: 2026,
    category: 'ip',
    services: ['Writing', 'Direction', '3D Animation', 'Sound Design'],
    thumbnail: '/assets/corgi-poster.png',
    gradient: 'linear-gradient(135deg, #1a0a00 0%, #cc6600 30%, #ff9933 50%, #0a0a0b 100%)',
    videoUrl: '/assets/ip-corgi.mp4',
    caseStudy: {
      challenge: { vi: 'Kể chuyện về một chú corgi mập mạp sống trong khu tập thể Hà Nội phải chạm đến cảm xúc và mang tính Việt Nam sâu sắc.', en: 'Telling the story of a chubby corgi living in a Hanoi apartment complex must be emotionally touching and deeply Vietnamese.' },
      approach: { vi: 'Silent comedy format 15 giây, tận dụng visual storytelling thuần túy, không cần lời thoại để vượt qua rào cản ngôn ngữ.', en: '15-second silent comedy format, leveraging pure visual storytelling, no dialogue needed to cross language barriers.' },
      outcome: { vi: 'Series viral trên TikTok với hàng triệu views, nhận được nhiều đề nghị hợp tác licensing.', en: 'Series went viral on TikTok with millions of views, received multiple licensing collaboration offers.' },
    },
    credits: [
      { role: 'Creator', name: 'StoryMee Studio' },
      { role: 'Story', name: 'StoryMee Writing Team' },
      { role: 'Animation', name: 'StoryMee Animation' },
    ],
  },
  {
    slug: 'tiny-world',
    title: { vi: 'TINY WORLD Thế Giới Vi Khuẩn', en: 'TINY WORLD The Microbe World' },
    client: 'StoryMee Original IP',
    year: 2026,
    category: 'ip',
    services: ['Concept Design', '3D Animation', 'World Building', 'Education Content'],
    thumbnail: '/assets/tinyworld-poster.png',
    gradient: 'linear-gradient(135deg, #1a0011 0%, #3d0026 30%, #990033 50%, #0a0a0b 100%)',
    videoUrl: '/assets/ip-virus.mp4',
    caseStudy: {
      challenge: { vi: 'Mỗi tập đưa khán giả vào một góc nhìn bất ngờ của những đồ vật nhỏ bé trong Tiny World.', en: 'Each episode brings the audience into an unexpected perspective of tiny objects in Tiny World.' },
      approach: { vi: 'Nhân cách hóa các đồ vật và vi khuẩn thành các nhân vật đáng yêu với tính cách riêng, đặt trong thế giới vi mô đầy màu sắc.', en: 'Personifying objects and bacteria into lovable characters with unique personalities, set in a colorful microscopic world.' },
      outcome: { vi: 'Được đánh giá cao về tính sáng tạo và góc nhìn mới lạ, đầy bất ngờ cho khán giả.', en: 'Highly praised for its creativity and fresh, unexpected perspectives for the audience.' },
    },
    credits: [
      { role: 'Creator', name: 'StoryMee Studio' },
      { role: 'Science Advisor', name: 'StoryMee Education' },
      { role: '3D Animation', name: 'StoryMee Animation' },
    ],
  },
  {
    slug: 'boing',
    title: { vi: 'BOING', en: 'BOING' },
    client: 'StoryMee Original IP',
    year: 2026,
    category: 'ip',
    services: ['Concept Design', '3D Animation'],
    thumbnail: '/assets/boing-poster.png',
    gradient: 'linear-gradient(135deg, #001a1a 0%, #003d3d 25%, #008080 50%, #00BCD4 80%, #0a0a0b 100%)',
    videoUrl: '/assets/boing-teaser.mp4',
    caseStudy: {
      challenge: { vi: 'Tạo ra những con vật béo tròn, mềm như bóng cao su với những chuyển động vật lý hài hước.', en: 'Creating round, chubby animals soft as rubber balls with humorous physical movements.' },
      approach: { vi: 'Tập trung vào vật lý của cơ thể để tạo sự hài hước, ra mắt dưới dạng clip 15 giây không lời thoại để dễ viral.', en: 'Focusing on body physics to create humor, launching as 15-second silent clips for easy virality.' },
      outcome: { vi: 'Trở thành một IP dễ viral, vượt qua rào cản văn hóa.', en: 'Became an easily viral IP, breaking cultural barriers.' },
    },
    credits: [
      { role: 'Creator', name: 'StoryMee Studio' },
    ],
  },
  {
    slug: 'midimouse',
    title: { vi: 'MIDIMOUSE', en: 'MIDIMOUSE' },
    client: 'StoryMee Original IP',
    year: 2026,
    category: 'ip',
    services: ['Concept Design', 'Animation', 'Music Production'],
    thumbnail: '/assets/midimouse-poster.png',
    gradient: 'linear-gradient(135deg, #1a001a 0%, #3d003d 25%, #800080 50%, #9C27B0 80%, #0a0a0b 100%)',
    videoUrl: '/assets/midimouse-episodes.mp4',
    caseStudy: {
      challenge: { vi: 'Tạo một nhân vật mang tính giải trí và giáo dục, học mà chơi qua âm nhạc.', en: 'Creating an entertaining and educational character, learning and playing through music.' },
      approach: { vi: 'Xây dựng chú chuột nhỏ yêu ca hát, mang đến những tình huống bất ngờ qua các bài học đầu đời.', en: 'Building a little singing mouse that brings unexpected situations through early childhood lessons.' },
      outcome: { vi: 'Trở thành người bạn đồng hành của trẻ nhỏ, học tập qua giai điệu vui tươi.', en: 'Became a companion for young children, learning through cheerful melodies.' },
    },
    credits: [
      { role: 'Creator', name: 'StoryMee Studio' },
    ],
  },
  {
    slug: 'storymee-film',
    title: { vi: 'StoryMee Film Production', en: 'StoryMee Film Production' },
    client: 'StoryMee Studio',
    year: 2026,
    category: 'production',
    services: ['Direction', 'Cinematography', 'Post Production', 'Color Grading'],
    thumbnail: '/placeholder.jpg',
    gradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a0a3e 30%, #2d1b69 50%, #0a0a0b 100%)',
    videoUrl: '/assets/film.mp4',
    caseStudy: {
      challenge: { vi: 'Sản xuất phim ngắn chất lượng cao thể hiện năng lực production của StoryMee ngoài animation.', en: 'Producing high-quality short film showcasing StoryMee\'s production capabilities beyond animation.' },
      approach: { vi: 'Kết hợp kỹ thuật quay phim điện ảnh với post-production tiên tiến, tạo ra sản phẩm có giá trị nghệ thuật cao.', en: 'Combining cinematic filming techniques with advanced post-production, creating high artistic value products.' },
      outcome: { vi: 'Mở rộng portfolio của StoryMee sang lĩnh vực film production, thu hút thêm khách hàng mới.', en: 'Expanded StoryMee\'s portfolio into film production, attracting new clients.' },
    },
    credits: [
      { role: 'Direction', name: 'StoryMee Studio' },
      { role: 'Cinematography', name: 'StoryMee Production' },
    ],
  },
  {
    slug: 'skinbibi-commercial',
    title: { vi: 'Skinbibi', en: 'Skinbibi' },
    client: 'Nam Hà Pharma',
    year: 0,
    category: 'commercial',
    services: ['2D Animation', 'Direction', 'Production', 'Post Production'],
    thumbnail: '/placeholder.jpg',
    gradient: 'linear-gradient(135deg, #0a1a2a 0%, #1a3a5a 30%, #2d5a8a 50%, #0a0a0b 100%)',
    videoUrl: '/assets/skinbibi.mp4',
    caseStudy: {
      challenge: { vi: 'Một sản phẩm 2D về chuyện gia đình, làm mẹ và bố.', en: 'A 2D product about family life, being a mother and father.' },
      approach: { vi: 'Kết hợp hoạt hình 2D với câu chuyện gia đình gần gũi, truyền tải thông điệp ấm áp về tình cảm gia đình.', en: 'Combining 2D animation with relatable family stories, conveying warm messages about family love.' },
      outcome: { vi: 'Phát sóng rộng rãi trên truyền hình, tăng độ nhận diện thương hiệu.', en: 'Widely broadcasted on television, increased brand awareness.' },
    },
    credits: [
      { role: 'Client', name: 'Nam Hà Pharma' },
      { role: 'Agency', name: 'Mix Digital' },
      { role: 'Producer & Script', name: 'Kim Ngân' },
      { role: 'Art Director', name: 'Trần Phúc Bảo' },
      { role: 'Animator', name: 'Hoà Triệu' },
    ],
  },
  {
    slug: 'amanoi-commercial',
    title: { vi: 'Amanoi Resort', en: 'Amanoi Resort' },
    client: 'Fly Amazing Stay & Partner Amanoi Resort',
    year: 0,
    category: 'commercial',
    services: ['Direction', 'Cinematography', 'Post Production'],
    thumbnail: '/placeholder.jpg',
    gradient: 'linear-gradient(135deg, #0a1a1a 0%, #1a3a3a 30%, #2d5a5a 50%, #0a0a0b 100%)',
    videoUrl: '/assets/amanoi.mp4',
    caseStudy: {
      challenge: { vi: 'Sản xuất video quảng bá vẻ đẹp và sự bình yên của Amanoi Resort.', en: 'Producing a promotional video showcasing the beauty and serenity of Amanoi Resort.' },
      approach: { vi: 'Quay phim góc rộng kết hợp với âm nhạc nhẹ nhàng, mang lại cảm giác thư thái cho người xem.', en: 'Wide-angle cinematography combined with soothing music to bring a relaxing feel to the audience.' },
      outcome: { vi: 'Video nhận được nhiều phản hồi tích cực từ khách hàng và đối tác.', en: 'The video received highly positive feedback from clients and partners.' },
    },
    credits: [
      { role: 'Client', name: 'Fly Amazing Stay & Partner Amanoi Resort' },
      { role: 'Producer', name: 'Kim Ngân' },
      { role: 'Director', name: 'Tuấn Đức' },
      { role: 'D.O.P', name: 'Sơn Hoàng' },
      { role: 'Cam.Op', name: 'Nguyễn Hữu Bảo Nhân' },
      { role: 'Equipment', name: 'Hải Cóc' },
      { role: 'Cast', name: 'Dang Quynh Chi, EnZo Ng' },
      { role: 'Make-up', name: 'Nguyen Diep' },
      { role: 'Stylist', name: 'Linh Rin' },
    ],
  },
  {
    slug: '1010-years-thang-long',
    title: { vi: '1010 Years Thang Long Hanoi', en: '1010 Years Thang Long Hanoi' },
    client: 'Orient Vietnam',
    year: 0,
    category: 'commercial',
    services: ['Direction', 'Production', 'Editing'],
    thumbnail: '/placeholder.jpg',
    gradient: 'linear-gradient(135deg, #2a0a0a 0%, #5a1a1a 30%, #8a2d2d 50%, #0a0a0b 100%)',
    videoUrl: '/assets/thang-long.mp4',
    caseStudy: {
      challenge: { vi: 'Tiếng kim đồng hồ hòa cùng nhịp sống Hà Nội nghìn năm, từ Tháp Rùa rêu phong soi bóng Hồ Gươm, đến mái ngói phố cổ nhuộm nắng chiều thu. Mỗi chiếc đồng hồ là một lát cắt Thăng Long. Đeo trên tay không chỉ là đồng hồ mà là cả một Hà Nội ngàn năm văn hiến.', en: 'The ticking of a watch harmonizes with the thousand-year rhythm of Hanoi, from the moss-covered Turtle Tower reflecting on Hoan Kiem Lake to the ancient tiled roofs bathed in autumn sunlight. Each watch is a slice of Thang Long. Wearing it is not just wearing a watch it is wearing a thousand years of Hanoi\'s heritage.' },
      approach: { vi: 'Tập trung vào các khung hình mang tính biểu tượng và văn hóa của thủ đô.', en: 'Focusing on iconic and cultural frames of the capital.' },
      outcome: { vi: 'Sản phẩm mang đậm dấu ấn lịch sử, được lan truyền rộng rãi.', en: 'A culturally significant product that was widely shared.' },
    },
    credits: [
      { role: 'Production', name: 'StoryMee Studio' },
    ],
  },
  {
    slug: 'your-vietnam-teaser',
    title: { vi: 'Your Vietnam Teaser', en: 'Your Vietnam Teaser' },
    client: 'Your Vietnam',
    year: 0,
    category: 'commercial',
    services: ['Cinematography', 'Editing'],
    thumbnail: '/placeholder.jpg',
    gradient: 'linear-gradient(135deg, #0a2a0a 0%, #1a5a1a 30%, #2d8a2d 50%, #0a0a0b 100%)',
    videoUrl: '/assets/your-vietnam.mp4',
    caseStudy: {
      challenge: { vi: 'Nghe tiếng khèn H\'Mông vang vọng giữa đại ngàn Hà Giang, tiếng sóng vỗ rì rào ôm lấy vịnh Hạ Long lúc bình minh. Nghe tiếng rao đêm Hà Nội nao lòng người xa xứ, tiếng chuông chùa Thiên Mụ ngân nga trên dòng Hương giang. Nghe tiếng đàn bầu rung động giữa đêm Hội An đèn lồng, tiếng cười giòn tan của lũ trẻ chân trần đuổi nhau trên cánh đồng lúa chín Mù Cang Chải. Nghe tiếng ghe xuồng khua nước miền Tây, tiếng mẹ ru à ơi vọng về từ miền ký ức.', en: 'Hear the H\'Mong flute echoing through Ha Giang\'s vast mountains, the waves gently embracing Ha Long Bay at dawn. Hear the night vendors\' calls in Hanoi touching the hearts of those far from home, the bells of Thien Mu Pagoda resonating over the Perfume River.' },
      approach: { vi: 'Từng thước phim được quay bằng cả trái tim từ flycam vút lên đỉnh Fansipan kiêu hãnh, đến cận cảnh giọt mồ hôi lăn trên gò má người nông dân. Từ ánh hoàng hôn nhuộm vàng ruộng bậc thang, đến khoảnh khắc ánh mắt em bé vùng cao chạm vào ống kính trong veo như giọt sương đầu núi.', en: 'Every frame was shot with heart from drones soaring to the proud peak of Fansipan, to close-ups of sweat rolling down a farmer\'s cheek. From golden sunsets dyeing terraced fields, to the moment a highland child\'s eyes meet the lens as clear as morning dew on the mountaintop.' },
      outcome: { vi: 'Đây không chỉ là một video. Đây là bản giao hưởng của núi sông, là hơi thở của 4000 năm văn hiến, là lời tri ân gửi đến mảnh đất đã sinh ra và nuôi dưỡng chúng ta.', en: 'This is not just a video. This is a symphony of mountains and rivers, the breath of 4000 years of civilization, a tribute to the land that gave birth to and nurtured us.' },
    },
    credits: [
      { role: 'Production', name: 'StoryMee Studio' },
    ],
  },
  {
    slug: 'ai-production-clip',
    title: { vi: 'StoryMee Studio Photo to Film', en: 'StoryMee Studio Photo to Film' },
    client: 'StoryMee Studio',
    year: 0,
    category: 'post_production',
    services: ['AI Generation', 'VFX', 'Editing', 'Photo Animation'],
    thumbnail: '/placeholder.jpg',
    gradient: 'linear-gradient(135deg, #1a2a3a 0%, #3a4a5a 30%, #5a6a7a 50%, #0a0a0b 100%)',
    videoUrl: '/assets/ai-production.mp4',
    caseStudy: {
      challenge: { vi: 'Chúng tôi nhận những bức ảnh raw, biến những bức ảnh có chuyển động, và tạo thành một thước phim kỉ niệm cũ. Có những kỷ niệm chỉ kịp đọng lại trong một bức ảnh tĩnh. Một nụ cười của bà, ánh mắt của mẹ, khoảnh khắc tuổi thơ bên hiên nhà cũ tất cả nằm im lặng trong khung hình đã ngả màu thời gian.', en: 'We take raw photos, bring movement to them, and create a nostalgic film reel. Some memories only survive in a single still photo. Grandmother\'s smile, mother\'s gaze, childhood moments on the old porch all lying silent in time-faded frames.' },
      approach: { vi: 'Chúng tôi ở đây để thổi hồn vào những bức ảnh ấy. Từ những tấm ảnh raw, chúng tôi mang lại chuyển động, ánh nhìn, hơi thở biến khoảnh khắc tĩnh thành thước phim sống động, để bạn được gặp lại chứ không chỉ nhìn lại.', en: 'We are here to breathe life into those photos. From raw images, we bring movement, gaze, breath turning still moments into vivid films, so you can meet again, not just look back.' },
      outcome: { vi: 'Khi không ai kịp bấm máy quay, khi ký ức chỉ còn là vài tấm ảnh ố vàng chúng tôi giúp bạn dựng lại cả một miền nhớ.', en: 'When no one had time to press record, when memories are just a few yellowed photos we help you reconstruct an entire realm of memory.' },
    },
    credits: [
      { role: 'Production', name: 'StoryMee Studio' },
    ],
  },

  {
    slug: 'song-cau-town',
    title: { vi: 'Sông Cầu Town Phú Yên', en: 'Song Cau Town Phu Yen' },
    client: 'Nam Bình Group',
    year: 0,
    category: 'commercial',
    services: ['Cinematography', 'Editing'],
    thumbnail: '/placeholder.jpg',
    gradient: 'linear-gradient(135deg, #1a2a1a 0%, #3a4a3a 30%, #5a6a5a 50%, #0a0a0b 100%)',
    videoUrl: '/assets/song-cau-town.mp4',
    caseStudy: {
      challenge: { vi: 'Một sản phẩm về quảng bá du lịch, thúc đẩy truyền thông địa phương được thực hiện bởi Nam Bình Group.', en: 'A tourism promotion product, boosting local media, produced by Nam Binh Group.' },
      approach: { vi: 'Sử dụng flycam và các góc máy rộng.', en: 'Using drone and wide-angle shots.' },
      outcome: { vi: 'Video quảng bá du lịch hấp dẫn.', en: 'An attractive tourism promotional video.' },
    },
    credits: [
      { role: 'Production', name: 'Nam Bình Group' },
    ],
  },
  {
    slug: 'storymee-book',
    title: { vi: 'StoryMee Book', en: 'StoryMee Book' },
    client: 'StoryMee Original',
    year: 2026,
    category: 'book',
    services: ['Publishing', 'Illustration', 'Storytelling'],
    thumbnail: '/assets/book.jpg',
    gradient: 'linear-gradient(135deg, #1a0a00 0%, #3d1c00 30%, #8B4513 50%, #0a0a0b 100%)',
    externalUrl: 'https://storymee.com/',
    caseStudy: {
      challenge: { vi: 'Mở rộng thế giới nhân vật StoryMee thông qua sách thiếu nhi.', en: 'Expanding the StoryMee character universe through children\'s books.' },
      approach: { vi: 'Kết hợp hình ảnh minh họa chất lượng cao với câu chuyện giàu ý nghĩa giáo dục.', en: 'Combining high-quality illustrations with meaningful educational stories.' },
      outcome: { vi: 'Sách nhận được sự yêu mến từ hàng ngàn độc giả nhí.', en: 'The book received love from thousands of young readers.' },
    },
    credits: [
      { role: 'Creator', name: 'StoryMee Studio' },
    ],
  },
  {
    slug: 'storymee-podcast',
    title: { vi: 'StoryMee Podcast', en: 'StoryMee Podcast' },
    client: 'StoryMee Original',
    year: 2026,
    category: 'podcast',
    services: ['Audio Production', 'Storytelling', 'Sound Design'],
    thumbnail: '/placeholder.jpg',
    gradient: 'linear-gradient(135deg, #001a1a 0%, #003d3d 30%, #008080 50%, #0a0a0b 100%)',
    caseStudy: {
      challenge: { vi: 'Mang đến trải nghiệm âm thanh sống động cho các câu chuyện.', en: 'Bringing an immersive audio experience to the stories.' },
      approach: { vi: 'Đầu tư kỹ lưỡng vào âm thanh, lồng tiếng và âm nhạc nền.', en: 'Careful investment in sound design, voice acting, and background music.' },
      outcome: { vi: 'Kênh podcast được nhiều thính giả yêu thích.', en: 'The podcast channel is loved by many listeners.' },
    },
    credits: [
      { role: 'Production', name: 'StoryMee Audio' },
    ],
  },
];

// ========== STORYMEE IPs ==========
export const ips: IP[] = [
  {
    slug: 'paco',
    name: { vi: 'PACO', en: 'PACO' },
    tagline: { vi: 'Chú vẹt nhỏ, trái tim lớn.', en: 'Small parrot, big heart.' },
    status: 'production',
    brandColor: '#4CAF50',
    gradient: 'linear-gradient(135deg, #0a1a0a 0%, #1b3d1b 25%, #2d692d 50%, #4CAF50 80%, #0a0a0b 100%)',
    keyVisual: '/assets/paco/ip-paco.jpg',
    videoUrl: '/assets/paco/paco-episodes.mp4',
    worldDescription: {
      vi: 'Paco là chú vẹt ngây thơ, luôn "hiểu sai nhưng trung thành tuyệt đối", đồng hành suốt đời với ông chủ cáu kỉnh và qua vô số biến cố đã âm thầm giúp ông trưởng thành, tìm lại cảm xúc và ý nghĩa cuộc sống. Paco là một IP giáo dục tiếng Anh hài hước giúp người xem học từ vựng và phát âm một cách tự nhiên.',
      en: 'Paco is a naive parrot who always "misunderstands but is absolutely loyal", accompanying his grumpy owner throughout life and through countless ups and downs, quietly helping him grow, rediscover emotions and the meaning of life. Paco is a humorous English education IP that helps viewers learn vocabulary and pronunciation naturally.',
    },
    gallery: [
      '/assets/paco/cute-paco.jpg',
      '/assets/paco/young-paco.jpg',
      '/assets/paco/exp-paco.jpg',
    ],
    characters: [
      { name: { vi: 'Paco Nhỏ', en: 'Cute Paco' }, role: 'Phiên bản nhỏ', bio: { vi: 'Paco lúc còn nhỏ ngây thơ, tò mò, mắt tròn xoe và luôn lạc quan.', en: 'Baby Paco innocent, curious, round-eyed and always optimistic.' }, gradient: 'linear-gradient(135deg, #4CAF50, #81C784)', image: '/assets/paco/cute-paco.jpg' },
      { name: { vi: 'Paco Trưởng Thành', en: 'Young Paco' }, role: 'Phiên bản lớn', bio: { vi: 'Paco trưởng thành tự tin, trung thành, luôn bên cạnh ông chủ qua mọi biến cố.', en: 'Grown-up Paco confident, loyal, always by his owner\'s side through every challenge.' }, gradient: 'linear-gradient(135deg, #2d692d, #4CAF50)', image: '/assets/paco/young-paco.jpg' },
      { name: { vi: 'Paco Già', en: 'Exp Paco' }, role: 'Phiên bản già', bio: { vi: 'Paco về già đôi mắt hiền từ, lông hơi bạc, mang theo cả đời ký ức bên ông chủ.', en: 'Elder Paco wise eyes, slightly greyed feathers, carrying a lifetime of memories with his owner.' }, gradient: 'linear-gradient(135deg, #1b3d1b, #2d692d)', image: '/assets/paco/exp-paco.jpg' },
    ],
    episodes: [
      { number: 1, title: { vi: 'Ngày đầu tiên bay', en: 'First Day of Flight' }, synopsis: { vi: 'Paco lần đầu tiên học bay và gặp những người bạn mới.', en: 'Paco learns to fly for the first time and meets new friends.' }, runtime: 420, releaseDate: '2025-06-01', gradient: 'linear-gradient(135deg, #4CAF50, #2d692d)' },
    ],
    licensingEnabled: true,
    tractionStats: { views: '1M+', awards: '2 Festival Nominations', fanBase: '80K' },
  },
  {
    slug: 'bigpaw',
    name: { vi: 'BIGPAW', en: 'BIGPAW' },
    tagline: { vi: 'Khám phá niềm vui chậm rãi', en: 'Discovering the slow joy' },
    status: 'production',
    brandColor: '#8D6E63',
    gradient: 'linear-gradient(135deg, #1a0e00 0%, #3d2800 25%, #8B6914 50%, #8D6E63 80%, #0a0a0b 100%)',
    keyVisual: '/assets/bear-poster.jpeg',
    videoUrl: '/assets/ip-bear.mp4',
    worldDescription: {
      vi: 'Sống giữa thế giới đầy đồ điện tử thông minh nhưng đôi tay to vụng về khiến mọi thiết bị high-tech đều hỏng. Chán nản, Bigpaw quay về dùng đồ cổ analog, và khám phá niềm vui chậm rãi của thế giới cũ. Hoạt hình không lời, format 30 60 giây.',
      en: 'Living in a world full of smart electronics but his big clumsy hands break every high-tech device. Frustrated, Bigpaw returns to using analog antiques, and discovers the slow joy of the old world. Silent animation, 30-60 second format.',
    },
    characters: [
      { name: { vi: 'Bigpaw', en: 'Bigpaw' }, role: 'Main Character', bio: { vi: 'Đôi tay to vụng về nhưng mang trái tim ấm áp.', en: 'Big clumsy hands but a warm heart.' }, gradient: 'linear-gradient(135deg, #3d2800, #8D6E63)' },
    ],
    episodes: [],
    licensingEnabled: true,
    tractionStats: { views: '2M+', awards: '1 Award', fanBase: '120K' },
  },
  {
    slug: 'corgi',
    name: { vi: 'Ú', en: 'Ú CORGI' },
    tagline: { vi: 'Mập mạp, đáng yêu, và rất Việt Nam.', en: 'Chubby, adorable, and very Vietnamese.' },
    status: 'released',
    brandColor: '#FF9800',
    gradient: 'linear-gradient(135deg, #1a0a00 0%, #3d1c00 25%, #cc6600 50%, #FF9800 80%, #0a0a0b 100%)',
    keyVisual: '/assets/corgi-poster.png',
    videoUrl: '/assets/ip-corgi.mp4',
    worldDescription: {
      vi: 'Chú Corgi láu cá, hậu đậu, lười biếng nhưng dễ thương trong khu tập thể Hà Nội sống cùng cô chủ, những người hàng xóm vui vẻ và hạnh phúc với các tình huống thường ngày. Hoạt hình không lời, độ dài 15s.',
      en: 'A mischievous, clumsy, lazy but adorable Corgi living in a Hanoi apartment complex with his owner and cheerful neighbors, happy with everyday situations. Silent animation, 15s length.',
    },
    gallery: [
      '/assets/corgi/env1.jpg',
      '/assets/corgi/env2.png',
      '/assets/corgi/env3.jpg',
      '/assets/corgi/env4.png',
    ],
    characters: [
      { name: { vi: 'Ú', en: 'Ú' }, role: 'Main Character', bio: { vi: 'Chó corgi mập ú với chiếc vòng cổ xanh, ham ăn và luôn gây rắc rối đáng yêu.', en: 'Chubby corgi with a blue collar, food-loving and always causing adorable trouble.' }, gradient: 'linear-gradient(135deg, #cc6600, #FF9800)', image: '/assets/corgi/u.png' },
      { name: { vi: 'Cô Thảo', en: 'Cô Thảo' }, role: 'Chủ của Ú', bio: { vi: 'Cô gái trẻ yêu động vật, luôn phải đau đầu giải quyết những rắc rối do Ú gây ra.', en: 'A young girl who loves animals, always having a headache solving the troubles Ú causes.' }, gradient: 'linear-gradient(135deg, #e91e63, #ff6090)', image: '/assets/corgi/thao.png' },
      { name: { vi: 'Bà Tâm', en: 'Bà Tâm' }, role: 'Hàng xóm', bio: { vi: 'Bà hàng xóm thân thiện, thường xuyên cho Ú ăn vặt.', en: 'Friendly neighbor who frequently gives Ú snacks.' }, gradient: 'linear-gradient(135deg, #4caf50, #81c784)', image: '/assets/corgi/batam.png' },
      { name: { vi: 'Ông Bình', en: 'Ông Bình' }, role: 'Hàng xóm', bio: { vi: 'Ông lão khó tính nhưng thực ra rất quý Ú.', en: 'A grumpy old man who actually adores Ú.' }, gradient: 'linear-gradient(135deg, #607d8b, #90a4ae)', image: '/assets/corgi/ongbinh.png' },
      { name: { vi: 'Mướp', en: 'Mướp' }, role: 'Đối thủ', bio: { vi: 'Chú mèo hàng xóm sang chảnh, kẻ thù không đội trời chung của Ú.', en: 'The fancy neighborhood cat, Ú\'s arch-nemesis.' }, gradient: 'linear-gradient(135deg, #ffc107, #ffd54f)', image: '/assets/corgi/muop.jpg' },
    ],
    episodes: [
      { number: 1, title: { vi: 'Corgi Episodes', en: 'Corgi Episodes' }, synopsis: { vi: 'Ú cố gắng lấy trộm bánh mì từ bà hàng xóm.', en: 'Ú tries to steal bread from the neighbor lady.' }, runtime: 15, releaseDate: '2024-01-15', gradient: 'linear-gradient(135deg, #FF9800, #cc6600)', videoUrl: '/assets/corgi-episodes.mp4' },
      { number: 2, title: { vi: 'Tắm hay không tắm', en: 'To Bath or Not to Bath' }, synopsis: { vi: 'Ú chạy trốn giờ tắm và gây náo loạn cả khu tập thể.', en: 'Ú escapes bath time and causes chaos in the apartment complex.' }, runtime: 15, releaseDate: '2024-01-22', gradient: 'linear-gradient(135deg, #cc6600, #3d1c00)' },
    ],
    licensingEnabled: true,
    tractionStats: { views: '5M+', awards: '3 Awards', fanBase: '200K+' },
  },
  {
    slug: 'tiny-world',
    name: { vi: 'TINY WORLD', en: 'TINY WORLD' },
    tagline: { vi: 'Góc nhìn bất ngờ từ những điều nhỏ bé.', en: 'Unexpected perspectives from small things.' },
    status: 'development',
    brandColor: '#E91E63',
    gradient: 'linear-gradient(135deg, #1a0011 0%, #3d0026 25%, #990033 50%, #E91E63 80%, #0a0a0b 100%)',
    keyVisual: '/assets/tinyworld-poster.png',
    videoUrl: '/assets/ip-virus.mp4',
    worldDescription: {
      vi: 'Mỗi tập đưa khán giả vào một góc nhìn bất ngờ: bên trong tủ lạnh lúc nửa đêm, cuộc sống của cục tẩy trên bàn học, hành trình của đồng xu rơi kẽ sofa. Đồ vật "sống dậy" với logic, nhịp sống và cộng đồng riêng mà mắt người lớn ít khi để ý.',
      en: 'Each episode brings the audience into an unexpected perspective: inside the fridge at midnight, the life of an eraser on a desk, the journey of a coin falling into a sofa crevice. Objects "come alive" with their own logic, pace of life, and community that adults rarely notice.',
    },
    characters: [],
    episodes: [],
    licensingEnabled: false,
    tractionStats: { views: '500K', awards: 'In Development', fanBase: '50K' },
  },
  {
    slug: 'boing',
    name: { vi: 'BOING', en: 'BOING' },
    tagline: { vi: 'Thế giới của những điều kỳ diệu', en: 'World of wonders' },
    status: 'production',
    brandColor: '#00BCD4',
    gradient: 'linear-gradient(135deg, #001a1a 0%, #003d3d 25%, #008080 50%, #00BCD4 80%, #0a0a0b 100%)',
    keyVisual: '/assets/boing-poster.png',
    videoUrl: '/assets/boing-teaser.mp4',
    worldDescription: {
      vi: 'Những con vật béo tròn, mềm như bóng cao su mỗi cú nhảy, mỗi bước đi đều \'boing boing\' đầy tính vật lý và hài hước. Hiện ra mắt dưới dạng clip 15 giây vừa đủ để gây cười, vừa dễ viral. Không lời thoại, không rào cản văn hóa.',
      en: 'Round, chubby animals as soft as rubber balls every jump, every step is a bouncy \'boing boing\' full of physics and humor. Currently released as 15-second clips just enough to be funny and easily viral. No dialogue, no cultural barriers.',
    },
    gallery: [
      '/assets/boing/alpine.png',
      '/assets/boing/arctic.png',
      '/assets/boing/cave.png',
      '/assets/boing/coast.png',
      '/assets/boing/deep_sea.png',
      '/assets/boing/desert.png',
      '/assets/boing/meadow.png',
      '/assets/boing/rainforest.png',
      '/assets/boing/savanna.png',
      '/assets/boing/swamp.png',
    ],
    characters: [
      { name: { vi: 'Berry', en: 'Berry' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #ff4081, #c51162)', image: '/assets/boing/berry.png' },
      { name: { vi: 'Bubbles', en: 'Bubbles' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #00bcd4, #006064)', image: '/assets/boing/bubbles.png' },
      { name: { vi: 'Cactus', en: 'Cactus' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #4caf50, #1b5e20)', image: '/assets/boing/cactus.png' },
      { name: { vi: 'Dune', en: 'Dune' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #ff9800, #e65100)', image: '/assets/boing/dune.png' },
      { name: { vi: 'Frosty', en: 'Frosty' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #e0f7fa, #00acc1)', image: '/assets/boing/frosty.png' },
      { name: { vi: 'Glide', en: 'Glide' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #7e57c2, #311b92)', image: '/assets/boing/glide.png' },
      { name: { vi: 'Mango', en: 'Mango' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #ffc107, #ff6f00)', image: '/assets/boing/mango.png' },
      { name: { vi: 'Moss', en: 'Moss' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #8bc34a, #33691e)', image: '/assets/boing/moss.png' },
      { name: { vi: 'Pearl', en: 'Pearl' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #f8bbd0, #c2185b)', image: '/assets/boing/pearl.png' },
      { name: { vi: 'Root', en: 'Root' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #795548, #3e2723)', image: '/assets/boing/root.png' },
      { name: { vi: 'Savanna Lion', en: 'Savanna Lion' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #ffab00, #bf360c)', image: '/assets/boing/savanna_lion.png' },
      { name: { vi: 'Tofu', en: 'Tofu' }, role: 'Character', bio: { vi: 'Tròn vo và đáng yêu.', en: 'Round and adorable.' }, gradient: 'linear-gradient(135deg, #f5f5f5, #9e9e9e)', image: '/assets/boing/tofu.png' },
    ],
    episodes: [],
    licensingEnabled: true,
    tractionStats: { views: '1.5M', awards: 'TBA', fanBase: '90K' },
  },
  {
    slug: 'midimouse',
    name: { vi: 'MIDIMOUSE', en: 'MIDIMOUSE' },
    tagline: { vi: 'Học mà chơi qua âm nhạc', en: 'Learn and play through music' },
    status: 'production',
    brandColor: '#9C27B0',
    gradient: 'linear-gradient(135deg, #1a001a 0%, #3d003d 25%, #800080 50%, #9C27B0 80%, #0a0a0b 100%)',
    keyVisual: '/assets/midimouse-poster.png',
    videoUrl: '/assets/midimouse-episodes.mp4',
    worldDescription: {
      vi: 'Chú chuột MIDIMouse là một chú chuột nhỏ thông minh, tinh nghịch nhưng vẫn giữ được sự lịch thiệp và duyên dáng. Sống giữa những không gian đời thường, MIDIMouse luôn mang đến những tình huống bất ngờ, hài hước nhưng cũng đầy khéo léo nhờ sự lanh lợi của mình. Đặc biệt, chú rất yêu thích ca hát mỗi hành động, mỗi câu chuyện đều như một giai điệu vui nhộn, lan tỏa năng lượng tích cực.\n\nKhông chỉ giải trí, MIDIMouse còn là người bạn đồng hành trong những bài học đầu đời dành cho trẻ nhỏ: từ thói quen sinh hoạt tốt (đánh răng, rửa tay, ngủ đúng giờ), kỹ năng ứng xử (lễ phép, chia sẻ, giúp đỡ người khác) đến việc khám phá thế giới xung quanh qua âm nhạc. Các nội dung ca nhạc được thể hiện đơn giản, dễ nhớ, giai điệu vui tươi, giúp trẻ vừa học vừa chơi một cách tự nhiên và hứng thú.',
      en: 'MIDIMouse is a smart, mischievous little mouse who maintains politeness and grace. Living in everyday spaces, MIDIMouse always brings unexpected, humorous, yet clever situations thanks to his agility. He especially loves singing every action and story is like a fun melody spreading positive energy.\n\nBeyond entertainment, MIDIMouse is a companion in early childhood lessons: from good daily habits (brushing teeth, washing hands, sleeping on time), behavioral skills (politeness, sharing, helping others) to discovering the world through music. The musical content is simple, memorable, and cheerful, helping children learn naturally and enthusiastically while playing.',
    },
    characters: [
      { name: { vi: 'MIDIMouse', en: 'MIDIMouse' }, role: 'Main Character', bio: { vi: 'Chú chuột nhỏ yêu ca hát.', en: 'Little mouse who loves singing.' }, gradient: 'linear-gradient(135deg, #800080, #9C27B0)' },
    ],
    episodes: [],
    licensingEnabled: true,
    tractionStats: { views: '3M+', awards: 'TBA', fanBase: '250K' },
  },
];

// ========== STORYMEE TEAM ==========
export const team: TeamMember[] = [
  {
    name: 'Trần Thị Kim Ngân',
    role: { vi: 'Founder', en: 'Founder' },
    bio: { 
      vi: 'Nhà sáng lập StoryMee, ấp ủ giấc mơ ghi dấu hoạt hình Việt trên bản đồ thế giới. Sống cùng những câu chuyện và miệt mài kiến tạo các IP mang bản sắc riêng. Định hướng chiến lược, "gác cổng" chất lượng nghệ thuật các thế giới IP.', 
      en: 'Founder of StoryMee, nurturing the dream of putting Vietnamese animation on the world map. Living with stories and diligently creating original IPs. Strategic direction, "gatekeeper" of the artistic quality of IP worlds.' 
    },
    gradient: 'linear-gradient(135deg, #1a1a2e, #3d3d5c)',
    image: '/assets/team/kim-ngan.jpg',
    social: { instagram: '#', linkedin: '#' },
  },
  {
    name: 'Lê Huy Đức Anh',
    role: { vi: 'Co-Founder', en: 'Co-Founder' },
    bio: { vi: 'Phụ trách công nghệ sản xuất, AI tools, quy trình kỹ thuật, R&D. Người "phù thủy" đứng sau quy trình sản xuất video của IP Studio. Anh biến những ý tưởng điên rồ nhất thành hiện thực bằng công nghệ, sáng tạo, và tình yêu với từng khung hình.', en: 'In charge of production technology, AI tools, technical processes, R&D. The "wizard" behind the IP Studio\'s video production process. He turns the craziest ideas into reality with technology, creativity, and love for every frame.' },
    gradient: 'linear-gradient(135deg, #2d1b69, #5c3d99)',
    image: '/assets/team/duc-anh.jpg',
    social: { linkedin: '#' },
  },
  {
    name: 'Giám đốc Sáng tạo',
    role: { vi: 'Creative Director', en: 'Creative Director' },
    bio: { vi: 'Giữ "linh hồn" nghệ thuật, đảm bảo mọi sản phẩm đồng nhất về phong cách và chất lượng.', en: 'Keeper of the artistic "soul", ensuring all products are consistent in style and quality.' },
    gradient: 'linear-gradient(135deg, #1b3d1b, #2d692d)',
    social: {},
  },
  {
    name: 'Producer',
    role: { vi: 'Production Manager', en: 'Production Manager' },
    bio: { vi: 'Điều phối dự án và quản lý quy trình sản xuất.', en: 'Project coordination and production process management.' },
    gradient: 'linear-gradient(135deg, #607d8b, #90a4ae)',
    social: {},
  },
  {
    name: 'Team Creative',
    role: { vi: 'IP Developers (3 người)', en: 'IP Developers (3 members)' },
    bio: { vi: 'Phát triển ý tưởng và kịch bản cho các IP gốc.', en: 'Developing ideas and scripts for original IPs.' },
    gradient: 'linear-gradient(135deg, #e91e63, #ff6090)',
    social: {},
  },
  {
    name: 'Team Production',
    role: { vi: 'Production (2 người)', en: 'Production (2 members)' },
    bio: { vi: 'Thực hiện diễn hoạt, dựng hình và hậu kỳ.', en: 'Handling animation, rendering, and post-production.' },
    gradient: 'linear-gradient(135deg, #ff9800, #ffb74d)',
    social: {},
  },
  {
    name: 'Team Growth',
    role: { vi: 'Growth (2 người)', en: 'Growth (2 members)' },
    bio: { vi: 'Phát triển cộng đồng và phân phối nội dung.', en: 'Community development and content distribution.' },
    gradient: 'linear-gradient(135deg, #4caf50, #81c784)',
    social: {},
  },
];

// ========== DEMO PRESS ==========
export const pressArticles: PressArticle[] = [
  { publication: 'Khởi Nghiệp', headline: 'Founder StoryMee Kim Ngân: Từ say mê AI rẽ sang làm "Sách độc bản" vì niềm vui của con', excerpt: 'Từng ấp ủ ước mơ dùng trí tuệ nhân tạo (AI) để tạo ra hàng loạt những ấn phẩm cho trẻ em, Kim Ngân phải dừng ngay ý tưởng chỉ sau vài tháng triển khai vì nhận ra vô vàn rào cản đến từ công nghệ.', date: '2026-01-15', url: 'https://khoinghiep.net.vn/founder-storymee-kim-ngan-a1214.html', lang: 'vi' },
  { publication: 'VnExpress', headline: 'Chú corgi Ú và giấc mơ animation Việt', excerpt: 'Series silent comedy 15 giây của StoryMee thu hút hàng triệu lượt xem trên mạng xã hội.', date: '2025-03-20', url: '#', lang: 'vi' },
  { publication: 'Animation Magazine', headline: 'StoryMee: Vietnam\'s Rising Animation Studio', excerpt: 'The studio\'s original IPs from a chubby corgi to a friendly virus are capturing hearts worldwide.', date: '2025-02-10', url: '#', lang: 'en' },
  { publication: 'Thanh Niên', headline: 'StoryMee và hành trình xây dựng IP animation Việt Nam', excerpt: 'Từ Paco đến Ú, mỗi nhân vật của StoryMee đều mang đậm bản sắc Việt nhưng có sức hấp dẫn toàn cầu.', date: '2024-12-05', url: '#', lang: 'vi' },
];

// ========== DEMO JOBS ==========
export const jobs: JobPosting[] = [
  {
    title: { vi: '3D Character Animator', en: '3D Character Animator' },
    department: 'Animation',
    location: 'Vietnam / Remote',
    type: 'Full-time',
    description: { vi: 'Tạo animation cho các nhân vật IP của StoryMee cần kinh nghiệm Maya/Blender.', en: 'Create animations for StoryMee\'s IP characters Maya/Blender experience required.' },
  },
  {
    title: { vi: 'Story Writer', en: 'Story Writer' },
    department: 'Story',
    location: 'Vietnam',
    type: 'Full-time',
    description: { vi: 'Viết kịch bản và phát triển câu chuyện cho các series animation.', en: 'Write scripts and develop stories for animation series.' },
  },
];

// ========== PRESS LOGOS ==========
export const pressLogos = [
  'Tuổi Trẻ', 'VnExpress', 'Animation Magazine', 'Thanh Niên',
  'Forbes Vietnam', 'Vietcetera', 'The Hollywood Reporter', 'Screen Daily'
];

// ========== CLIENT / PARTNER LOGOS ==========
export const clientLogos = [
  'YouTube Kids', 'TikTok', 'Netflix', 'Vidio',
  'FPT Play', 'VTV', 'Galaxy Play', 'POPS Kids'
];
